# These values shouldn't be changed during normal development. Instead, change values in `config-debug.yml` which will
# not affect production builds

services:
  generators:
    disabled:
      - 'javadoc'
      - 'groovydoc'
      - 'swiftdoc'
    externalIndices:
      - 'https://javaeden.github.io/Clog/meta/javadoc.index.json'
      - 'https://javaeden.github.io/Common/meta/javadoc.index.json'
      - 'https://copper-leaf.github.io/krow/meta/kotlindoc.index.json'

wiki:
  sections:
    'user-manual':
      createPdf: false
    'learn':
      createPdf: false