site:
  about:
    siteName: Orchid
    siteDescription: A beautiful and truly unique documentation engine and static site generator.
    avatar: 'assets/media/avatar.jpg'

theme:
  social:
    other:
      - link: 'https://orchid.netlify.com/'
        label: 'Home'
        icon: 'fas fa-home'
      - link: 'https://github.com/JavaEden/Orchid'
        label: 'Github'
        icon: 'fab fa-github'
      - link: 'https://twitter.com/OrchidSSG'
        label: 'Twitter'
        icon: 'fab fa-twitter'
  menu:
    - type: 'page'
      title: 'Home'
      itemId: 'Home'
    - type: 'wikiSections'
    - type: 'page'
      itemId: 'Changelog'
  sidebarBackground: 'primary'
  sidebarBackgroundType: GRADIENT
  colors:
    purple: '#7E83C4'
  palette:
    primary: 'PURPLE'
    link: 'BLUE'

services:
  publications:
    stages:
      - type: githubReleases
        repo: 'JavaEden/Orchid'

kotlindoc:
  sourceDirs:
    - '../../main/java'
    - '../../main/kotlin'

#allPages:
#  extraCss:
#    - "inline:sidecar.css: .gitter-chat-embed { margin-top: 50px; }"
#  extraJs:
#    - "inline:sidecar.js:((window.gitter = { }).chat = { }).options = { room: 'JavaEden/Orchid' }; "
#    - "https://sidecar.gitter.im/dist/sidecar.v1.js"

allPages:
  extraCss:
    - 'assets/css/plugins.scss'
  components:
    - type: "pageContent"
    - type: "prism"
      githubTheme: 'duotone-light'
      languages:
        - kotlin
        - java
        - groovy
        - yaml
