# Feel free to change any values in here as needed, they are overridden by `config-prod.yml` in full production builds.
# Typically, as much as possible is disabled so that iterative development is as quick as possible.

services:
  generators:
    disabled:
      - 'javadoc'
      - 'swiftdoc'
      - 'kotlindoc'
      - 'groovydoc'
#      - 'pages'
      - 'styleguide'
      - 'posts'
      - 'changelog'
      - 'forms'
      - 'presentations'
      - 'sitemap'
      - 'indices'
      - 'feeds'
      - 'taxonomies'
      - 'netlifyCms'

wiki:
  sections:
    'user-manual':
      createPdf: false
    'tutorials':
      createPdf: false
